version = 1

[[analyzers]]
name = "cfn-lint"
type = "community"

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "shell"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "vitest",
    "nodejs"
  ]

[[analyzers]]
name = "rust"

  [analyzers.meta]
  msrv = "stable"

[[code_formatters]]
name = "rustfmt"

[[code_formatters]]
name = "prettier"